//
//  ListBikesWireframe.swift
//  findBike
//
//  Created by Israel on 2/12/19.
//  Copyright (c) 2019 Israel. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ListBikesWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "ListBikes", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: ListBikesViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = ListBikesInteractor()
        let presenter = ListBikesPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ListBikesWireframe: ListBikesWireframeInterface {
    
    func navigate(to option: ListBikesNavigationOption, _ data: StationView, _ arrFind: [StationView]) {
        
        switch option {
        case .detail:
            goToDeail(data,arrFind)
        }
        
    }
    
    func navigate(to option: ListBikesNavigationOption) {
    }
    
    private func goToDeail(_ data: StationView, _ arrFind: [StationView]){
        
        let wireframe = DetailBikeWireframe()
        let vc = wireframe.viewController as! DetailBikeViewController
        vc.datos = data
        vc.arrStationsNear = arrFind
        navigationController?.pushWireframe(wireframe)
    }
    
}
