//
//  ListBikesInterfaces.swift
//  findBike
//
//  Created by Israel on 2/12/19.
//  Copyright (c) 2019 Israel. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import CoreLocation

enum ListBikesNavigationOption {
    case detail
}

protocol ListBikesWireframeInterface: WireframeInterface {
    func navigate(to option: ListBikesNavigationOption)
    func navigate(to option: ListBikesNavigationOption, _ data: StationView, _ arrFind: [StationView])
}

protocol ListBikesViewInterface: ViewInterface {
    func loginSucces(_ succes:Bool)
    func setDataView(_ arrBikes:[StationView])
    func succesStationsNearby(_ arrFind: [StationView])
}

protocol ListBikesPresenterInterface: PresenterInterface {
    func autenticate()
    func getStationsStatus()
    func getStations(_ location:CLLocation)
    func goToDetail(_ data: StationView, _ arrFind: [StationView])
    func getStationsNearby(_ id: NSNumber)
}

protocol ListBikesInteractorInterface: InteractorInterface {
    func autenticate(callback:@escaping CallbackResponseLogin)
    func getStationsStatus()
    func getStations(_ location:CLLocation,callback:@escaping CallbackStationsView)
    func getStationsNearby(_ id: NSNumber, callback:@escaping CallbackStationsView)
}
