//
//  DetailBikeInteractor.swift
//  findBike
//
//  Created by Israel on 2/15/19.
//  Copyright (c) 2019 Israel. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailBikeInteractor {
    
}

// MARK: - Extensions -

extension DetailBikeInteractor: DetailBikeInteractorInterface {
}
