//
//  DetailBikePresenter.swift
//  findBike
//
//  Created by Israel on 2/15/19.
//  Copyright (c) 2019 Israel. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailBikePresenter {

    // MARK: - Private properties -

    private unowned let _view: DetailBikeViewInterface
    private let _wireframe: DetailBikeWireframeInterface
    private let _interactor: DetailBikeInteractorInterface

    // MARK: - Lifecycle -

    init(wireframe: DetailBikeWireframeInterface, view: DetailBikeViewInterface, interactor: DetailBikeInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension DetailBikePresenter: DetailBikePresenterInterface {
}
