//
//  DetailBikeInterfaces.swift
//  findBike
//
//  Created by Israel on 2/15/19.
//  Copyright (c) 2019 Israel. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum DetailBikeNavigationOption {
}

protocol DetailBikeWireframeInterface: WireframeInterface {
    func navigate(to option: DetailBikeNavigationOption)
}

protocol DetailBikeViewInterface: ViewInterface {
}

protocol DetailBikePresenterInterface: PresenterInterface {
}

protocol DetailBikeInteractorInterface: InteractorInterface {
}
