//
//  DetailBikeWireframe.swift
//  findBike
//
//  Created by Israel on 2/15/19.
//  Copyright (c) 2019 Israel. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailBikeWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "DetailBike", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: DetailBikeViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = DetailBikeInteractor()
        let presenter = DetailBikePresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension DetailBikeWireframe: DetailBikeWireframeInterface {

    func navigate(to option: DetailBikeNavigationOption) {
    }
}
